### ISSUE TITLE
ruby not found. trying to find ruby in the path and not using embedded sensu version

### ISSUE THREAD

**Issue by frederic-joventures** [sensu-plugins/sensu-plugins-memcached#2]
Hello,
when trying to install I have a error ruby not found.

GMAKE_CMD='make' CXXFLAGS=' -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -std=gnu++98 -L/opt/sensu/embedded/lib -I/opt/sensu/embedded/include -fPIC -L/opt/sensu/embedded/lib -I/opt/sensu/embedded/include -fPIC' SOURCE_DIR='libmemcached-0.32' HERE='/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/memcached-1.8.0/ext' ruby ../extconf-make.rb
sh: 1: ruby: not found

I use the embedded ruby from sensu and do not have another version of ruby installed.

**Comment by eheydrick** [comment]
Which platform are you seeing this on?

**Comment by frederic-joventures** [comment]
Ubuntu 14.04 latest

**Comment by eheydrick** [comment]
I'm unable to repro this. Can you post the full command you are using to install the plugin.

**Comment by eheydrick** [comment]
@frederic-jomedia Were you able to get the install command?

**Comment by frederic-joventures** [comment]
sorry for the delay
I install using : 
/opt/sensu/embedded/bin/gem install sensu-plugins-memcached -v  0.0.3

[output.txt](https://github.com/sensu-plugins/sensu-plugins-memcached/files/135074/output.txt)

**Comment by sstarcher** [comment]
@frederic-jomedia my guess would be that `/opt/sensu/embedded/bin/ruby` is not on your path
Try adding it to your path prior to running the command.

Also check the output of `which ruby`

**Comment by frederic-joventures** [comment]
It is indeed the case but I only have the problem with this particular plugin. I suppose the others force the usage of the embedded ruby ?

**Comment by frederic-joventures** [comment]
I can confirm that the installation succeeded with sensu's ruby in the path.

**Comment by envintus** [comment]
FWIW, I did not experience this on Debian 8 Jessie. I went ahead and made sure that `libsasl2-dev` was installed and when I installed the plugin using `sensu-install` it worked with out error.

**Comment by frederic-joventures** [comment]
Since the sensu-install  (instead of calling gem directly ) command line it is working. So I guess it can be closed

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-memcached/issues/2#issuecomment-199826132
