### ISSUE TITLE
Can't connect to port 11211

### ISSUE THREAD

**Issue by nnsaln** [sensu-plugins/sensu-plugins-memcached#5]
Can't connect to port 11211 if used socket

**Comment by nnsaln** [comment]
I found the issue,
it's because line 
`stats[line.split(' ')[1]] = line.split(' ')[2] if line =~ 'STAT'`
change it into
`stats[line.split(' ')[1]] = line.split(' ')[2] if line =~ /stat/i`

**Comment by majormoses** [comment]
@nnsaln Thanks for finding and triaging this, any chance you could submit a PR to address this?

**Comment by majormoses** [comment]
@nnsaln I have created a PR for it, if you subscribe to it once it has been reviewed and released I will update it there.
